### ISSUE TITLE
Doubt: receiving a WhatsApp from 3 sources if has 3 subscribers

### ISSUE THREAD

**Issue by jader31** [notify-events/zabbix#7]
I create a channel with 1 source and 3 subscribers.
When Zabbix (the souce) send the message I got 3 messages on WhatsApp, one for each of subscribers.
I think it should send as my mobile phone (the authenticated device) and not this way.
Am I doing something wrong? Could you point it?

(sorry did not find any other way to request help and this MAY BE a bug)

**Comment by papajojo** [comment]
Hello @jader31,

Right now we see that notifications should be sent to every channel subscriber from your GreenAPI account. Could you write to us at support@notify.events and describe in more detail how you want this to work and what exactly is not right now? (maybe you could also take a screenshot).

Since this issue is not related to Zabbix (you are getting notification from Zabbix to Notify.Events), I am closing this issue. Let's continue with email.

Thank you for your request!
